# Generated by Django 4.1.4 on 2023-06-28 16:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file_operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploadmodel',
            name='file',
        ),
        migrations.AddField(
            model_name='fileuploadmodel',
            name='creation_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fileuploadmodel',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fileuploadmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Uploaded'), (1, 'Uploaded')], default=0),
        ),
        migrations.AlterField(
            model_name='fileuploadmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UploadedFileDetailsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload_file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_operation.fileuploadmodel')),
            ],
        ),
    ]
