version: '3'
services:
  django_backend:
    restart: always
    image: django_file_app
    container_name: django_file_app
    build:
      context: ./django_backend
    ports:
      - 4100:4100
    volumes:
      - ./django_backend:/app
    depends_on:
      - backend_db
      - redis_cache
  backend_db:
    restart: always
    container_name: mongo_backend_db
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./mongodb:/data/db
    ports:
      - 4200:27017
  redis_cache:
    restart: always
    container_name: redis_backend
    image: redis:latest
    ports:
      - 4300:6379
